#
# e72_beam.conf
#

BEAM:			param/BEAM/beam.k.run69_0130.root
DCGEO:			param/DCGEO/DCGeomParam_E72_0
DSIZE:			param/DSIZE/DetSize_E72_0
HIST:			param/HIST/HistParam_E72_0
#SHSFLDMAP:		fieldmap/ShsFieldMap_E42_20190625_1T
SHSFLDMAP:		fieldmap/ShsFieldMap_E42_20190903_1T
#SHSFLDMAP:		fieldmap/ShsFieldMap_20210526
#SHSFLDMAP:		fieldmap/ShsFieldMap_20210623

SHSFLDCALC:		1.0
SHSFLDNMR:		-1.0

EM:			0
HADRON:			0
DECAY:			1

##### General Parameter
Experiment:		72
BeamGenerator:		7201 # K- old beam data
DecayGenerator:         7202
TargetMaterial:		LH2
TargetVP:		1
BeamMom:		0.735 # GeV/c
CSFlat:                 1 #For acceptance study
# DefaultCutValue:	20 # mm
KillStepInIron:		1
##### SHS
ShsFieldMap:		1
ShsField:		1.0 # Tesla
##### HypTPC Parameter
TruncatedMeanCut:	0.3
